services:
  - name: backend
    type: web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatbot_db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: "your-app-name.onrender.com"

  - name: frontend
    type: web
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "serve -s build"
    staticPublishPath: "build"
    envVars:
      - key: REACT_APP_API_URL
        value: "https://your-backend-url.onrender.com"

databases:
  - name: learnfreedb
    plan: free
    postgresVersion: 16
