services:
  - type: web
    name: chatbot-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatbot-db
          property: connectionString

# databases:
#   - name: learfreedb
#     region: oregon
#     plan: free
#     databaseName: ch
#     user: chatbot_user
